// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRkwQfJbniYkckHStN8dA5Np0wjbjwiSM',
    appId: '1:73540728416:web:d1d0e1c62864878d527505',
    messagingSenderId: '73540728416',
    projectId: 'bookly-92893',
    authDomain: 'bookly-92893.firebaseapp.com',
    storageBucket: 'bookly-92893.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2BhCdUwXXOXZKgw-TCcobeVmLGhDbu-A',
    appId: '1:73540728416:android:cca99453042fcb54527505',
    messagingSenderId: '73540728416',
    projectId: 'bookly-92893',
    storageBucket: 'bookly-92893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8N7krNgiFn91SY7bKpQeExFa258_FXY',
    appId: '1:73540728416:ios:94ac3232ae5ca2d4527505',
    messagingSenderId: '73540728416',
    projectId: 'bookly-92893',
    storageBucket: 'bookly-92893.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb8N7krNgiFn91SY7bKpQeExFa258_FXY',
    appId: '1:73540728416:ios:94ac3232ae5ca2d4527505',
    messagingSenderId: '73540728416',
    projectId: 'bookly-92893',
    storageBucket: 'bookly-92893.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRkwQfJbniYkckHStN8dA5Np0wjbjwiSM',
    appId: '1:73540728416:web:26cd022dbd1b7e9c527505',
    messagingSenderId: '73540728416',
    projectId: 'bookly-92893',
    authDomain: 'bookly-92893.firebaseapp.com',
    storageBucket: 'bookly-92893.firebasestorage.app',
  );
}
